### ISSUE TITLE
[BUG] Cannot find name 'SpeechRecognition'

### ISSUE THREAD

**Issue by simon1389** [taiga-family/ng-web-apis#116]
# 🐞 Bug report

### Description

Can't start my Angular (v15) app due to unknown type 'SpeechRecognition'

### Versions
- Angular 15

### Additional context

![image](https://github.com/taiga-family/ng-web-apis/assets/9256689/00b54a41-4bcb-41d5-be7f-9667d45c8df0)

**Comment by sevaru** [comment]
This should be probably work with the new version: [3.0.4](https://www.npmjs.com/package/@ng-web-apis/speech/v/3.0.4). Please give it a try and inform us of any issues or feedback you have.

**Comment by RaimonxDev** [comment]
I have the same problem but angular version 17. any solution?  
![image](https://github.com/taiga-family/ng-web-apis/assets/39868803/7527c9d9-0c2b-4294-9ab8-e14aa067a69e)

Version: 
```
"@ng-web-apis/common": "^3.0.6",
"@ng-web-apis/speech": "^3.0.7",
"@angular/common": "17.0.2",
"@angular/compiler": "17.0.2",
"@angular/core": "17.0.2",
```
